Add font-size to floating-label-container
telerik/kendo-themes pull request #2000
Opened 2020-10-21 12:53 UTC by GeorgeGindev

Targets: https://github.com/telerik/kendo-themes/issues/1986

2020-10-21 13:49 UTC, PreslavKozovski approved these changes

2020-10-23 07:38 UTC, joneff requested changes
The fix will not solve the issue: what if there are styles targeting `.k-floating-label-container`? The outcome will still be the same.

Instead, look inside the floating label variables, more specifically `$floating-label-height`. It's currently based on `em` units, but you could very well base it on exact pixels, by passing the correct value when multiplying.

2020-10-27 11:54 UTC, GeorgeGindev commented
So if `.k-floating-label-container` is added `font-size`, is the correct behavior to apply the font-size to all inner elements like so https://dojo.telerik.com/iBOViLEg/8 , or should it have no effect on the inner elements with pixel values, like so https://dojo.telerik.com/iBOViLEg/9 ?

2020-11-03 07:00 UTC, joneff commented
@GeorgeGindev the floating label container is just that: a container. it's not like it can't have font size, it just doesn't, because it doesn't need to: apart from the floating label, the only other content item is the input and it has it's own set of variables.

Try to look at things this way: if I set floating label font size to be 20px and input font size to be 25, how do I expect them to apply inside a floating label container?

To me that means: the label is 20px and the input is 25.

Or to answer your question directly: https://dojo.telerik.com/iBOViLEg/9, to me, seems like the correct way to go.

2020-11-04 21:12 UTC, joneff approved these changes

2020-11-04 21:18 UTC, merged