test(floating-label): add visual tests
telerik/kendo-themes pull request #2063
Opened 2020-11-12 12:37 UTC by GeorgeGindev

Test for explicitly set font-size on floating-label-container #1986

2020-11-13 07:42 UTC, joneff approved these changes

2020-11-13 08:36 UTC, PreslavKozovski requested changes
We do not need to test all the states for this issue - https://github.com/telerik/kendo-themes/issues/1986

A single HTML test file is adding 3 PNGs.

Having said that, I would suggest adding one more row to this HTML file https://github.com/telerik/kendo-themes/blob/develop/tests/visual/floating-label.html

And removing the current `floating-label-container-font-size.html `

2020-11-13 10:33 UTC, PreslavKozovski approved these changes

2020-11-15 16:11 UTC, joneff approved these changes

2020-11-15 16:41 UTC, merged