Grid toolbar reworked with flex
telerik/kendo-themes pull request #2081
Opened 2020-11-18 09:04 UTC by GeorgeGindev

Targets #2037

2020-11-19 07:41 UTC, joneff requested changes

2020-11-19 07:41 UTC, joneff commented on packages/default/scss/grid/_layout.scss
> +                > * {
If we are using flex, we can use `gap`

2020-11-19 07:41 UTC, joneff commented on packages/default/scss/grid/_layout.scss
> +                margin-left: $grid-toolbar-spacing;
no need here for those.

see if you can manually place a spacer

2020-11-19 07:41 UTC, joneff commented on packages/default/scss/grid/_layout.scss
> +            margin-left: auto;
probably this will also not be needed

2020-11-19 07:41 UTC, joneff commented on tests/visual/grid-toolbar.html
> +                        <button class="k-button-icon k-button k-group-end"><span class="k-icon k-i-bold"></span></button>
Why? The first button is the start button. If for some reason the buttons do not look correctly, it's not issue of the class names, rather, the styles. You can look at the button-group styles for a fix.

2020-11-19 07:47 UTC, joneff commented
Quick question: we already have the styles for toolbar. What if we add the class for toolbar to the grid toolbar:

```html<!-- current -->
<div class="k-header k-grid-toolbar">
    ...
</div>


<!-- suggestion -->
<div class="k-toolbar k-grid-toolbar">
    ...
</div>
```

Looking at the styles for toolbar, that will make the items wrap on small resolutions with the appropriate spacing. Being a styled toolbar, we can also use spacers. Finally, that will also clean up some variables, as we won't need them [when we have the classnames for styling toolbar size and color wise].

@VicTachev @tapopov @Xizario @Raisolution @inikolova thoughts?

2020-12-08 07:33 UTC, joneff commented
@silviyaboteva @inikolova we'll be moving the styles to dev!

2020-12-08 08:27 UTC, joneff approved these changes

2020-12-08 08:29 UTC, PreslavKozovski approved these changes

2020-12-08 13:14 UTC, inikolova requested changes
Add **flex-shrink: 0** to **.k-grid-toolbar** otherwise toolbar squashes when the Grid is scrollable and small height is set

2020-12-08 16:38 UTC, inikolova approved these changes

2020-12-08 16:47 UTC, merged

2020-12-11 06:51 UTC, ivanchev commented
@joneff can myself and @jivanova get a mention when such changes are required in the future, since right now the Blazor Grid is broken, and we had no idea that this is going to happen.

2020-12-11 07:34 UTC, joneff commented
An oversight on my part. I thought I mentioned all managers in the previous comment.