fix(floatingactionbutton): line height issue in material and bootstra…
telerik/kendo-themes pull request #2097
Opened 2020-11-30 15:47 UTC by silviyaboteva

…p themes

2020-12-01 13:08 UTC, joneff approved these changes

2020-12-01 13:09 UTC, joneff commented
@silviyaboteva `floatingactionbutton` is quite a mouthful. You can use `fab` for commits. Developers will still know which component the fix is referring to ;)

2020-12-01 14:24 UTC, Juveniel approved these changes

2020-12-01 17:27 UTC, inikolova approved these changes

2020-12-03 14:46 UTC, joneff requested changes
the line height doesn't look good to me as value. we should perhaps find another approach

2020-12-07 21:40 UTC, joneff approved these changes

2020-12-07 21:56 UTC, merged