Scrollview improvements + keyboard navigation
telerik/kendo-themes pull request #2108
Opened 2020-12-03 12:49 UTC by GeorgeGindev

Kendo Item: https://github.com/telerik/kendo/issues/11785
UX behavior item - https://github.com/telerik/kendo-ux-private/issues/227, https://github.com/telerik/kendo-ux-private/issues/89

2020-12-04 09:36 UTC, PreslavKozovski requested changes
Check the below comments.

Also, in a real scenario, the pager hover does not look good. You should check why. For example: 
![image](https://user-images.githubusercontent.com/17339722/101147333-e72ada80-3624-11eb-9c53-842f149bb190.png)

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/default/scss/scrollview/_theme.scss
> +            top: -$scrollview-pagebutton-focused-border-width;
everything but the `border-color` should be part of the layout.

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/default/scss/scrollview/_theme.scss
> +        background: $scrollview-navigation-bg;
Use `background-color`

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/default/scss/scrollview/_theme.scss
> +        outline-width: 0;
Move `outline-width` to `layout`

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/default/scss/scrollview/_theme.scss
> +                border-width: $scrollview-pagebutton-focused-border-width;
Move these to `layout`

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/default/scss/scrollview/_layout.scss
No need in skipping two rows when nesting selectors in this case.

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/default/scss/scrollview/_layout.scss
>                  text-align: center;
This change is breaking the current logic of scrolling the pager buttons. To check it, use the following demo https://demos.telerik.com/kendo-ui/scrollview/api

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/bootstrap/scss/scrollview/_theme.scss
> +            }
Move "layout" pros to the `layout` file.

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/bootstrap/scss/scrollview/_theme.scss
> +        background: $scrollview-navigation-bg;
use `background-color`

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/bootstrap/scss/scrollview/_variables.scss
> +$scrollview-dark-bg: rgba(0, 0, 0, .2);
Add `!default;` so these variables could be overridden.

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/classic/scss/scrollview/_variables.scss
> +$scrollview-dark-bg: rgba(0, 0, 0, .2);
Add `!default;` so these variables could be overridden.

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/default/scss/scrollview/_variables.scss
> +$scrollview-dark-bg: rgba(0, 0, 0, .2);
Add `!default;` so these variables could be overridden.

2020-12-04 09:36 UTC, PreslavKozovski commented on packages/material/scss/scrollview/_variables.scss
> +$scrollview-dark-bg: rgba(0, 0, 0, .2);
Add `!default;` so these variables could be overridden.

2020-12-08 14:28 UTC, PreslavKozovski approved these changes

2020-12-08 18:00 UTC, inikolova commented
From my tests with the Angular ScrollView I observed the following:

- The default opacity of the pager buttons is changed;
- Hover behaviour is applied to the whole **k-scrollview-pageable** element, which changes the appearance of all buttons in the pager at the same time. Also, no hover effect for a separate page is applied;

2020-12-08 18:01 UTC, inikolova requested changes
From my tests with the Angular ScrollView I observed the following:

- The default opacity of the pager buttons is changed;

- Hover behaviour is applied to the whole k-scrollview-pageable element, which changes the appearance of all buttons in the pager at the same time. Also, no hover effect for a separate page is applied;

2020-12-11 07:25 UTC, joneff requested changes
To make things easier, consider that

* angular uses `ul.k-scrollview` and jquer uses `div.k-scrollview`
* both use `ul > li` for the navigation.

and finally, this component is getting really out of hand in terms of rendering and should be unified!

2020-12-11 07:25 UTC, joneff commented on packages/bootstrap/scss/scrollview/_theme.scss
> +    }
```suggestion
    .k-scrollview,
    .k-scrollview-wrap {
        outline: none;
    }
```

or if that doesn't work 

```suggestion
    .k-scrollview:focus,
    .k-scrollview-wrap:focus {
        outline: none;
    }
```

2020-12-11 07:25 UTC, joneff commented on packages/bootstrap/scss/scrollview/_theme.scss
> +        &.k-state-focused {
this is a new selector. prefer `k-state-focus`

2020-12-11 07:25 UTC, joneff commented on packages/bootstrap/scss/scrollview/_theme.scss
> +        &.k-state-hovered {
this is  anew selector. prefer `k-state-hover`

2020-12-11 07:25 UTC, joneff commented on packages/bootstrap/scss/scrollview/_theme.scss
> +    .k-scrollview .k-scrollview-nav > .k-link {
```suggestion
    .k-scrollview-pageable > .k-button,
    .k-scrollview-nav > .k-link {
```

should be sufficient

2020-12-11 07:25 UTC, joneff commented on packages/default/scss/scrollview/_layout.scss
> +                width: $scrollview-pagebutton-size - 6px;
do not assume the size is in pixels. use calc instead

2020-12-11 07:25 UTC, joneff commented on packages/default/scss/scrollview/_layout.scss
> +    .k-scrollview .k-scrollview-nav {
```suggestion
    .k-scrollview-pageable,
    .k-scrollview-nav {
```

Previously the selectors were shorter. use the same selectors

2020-12-11 07:25 UTC, joneff commented on packages/default/scss/scrollview/_layout.scss
> +    .k-scrollview .k-scrollview-nav > .k-link {
```suggestion
    .k-scrollview-pageable > .k-button,
    .k-scrollview-nav > .k-link {
```

use shorter selectors.

2020-12-11 07:25 UTC, joneff commented on packages/default/scss/scrollview/_layout.scss
> +            height: $scrollview-pagebutton-size + $scrollview-pager-item-spacing;
you are assuming compatible units.

2020-12-11 07:25 UTC, joneff commented on packages/default/scss/scrollview/_theme.scss
> +        -webkit-tap-highlight-color: $rgba-transparent;
Why? this is not an appearance thing. it belongs to the layout.

2020-12-11 07:25 UTC, joneff commented on packages/default/scss/scrollview/_theme.scss
> +            .k-icon::before {
```suggestion

            .k-icon::before {
```

leave a space for legibility.

2020-12-11 07:48 UTC, GeorgeGindev commented on packages/default/scss/scrollview/_layout.scss
> -        -webkit-tap-highlight-color: $rgba-transparent;
because it is a color, I thought it belongs to theme

2020-12-11 07:53 UTC, inikolova requested changes
EDIT: 
In Angular in RTL mode pager buttons **::before** elements are moved, so clicking a page selects the next one:
<img width="927" alt="Screenshot 2020-12-11 at 9 47 13" src="https://user-images.githubusercontent.com/1826086/101876895-daaf0080-3b95-11eb-8637-e35e0b74fb0e.png">
<img width="1049" alt="Screenshot 2020-12-11 at 9 47 27" src="https://user-images.githubusercontent.com/1826086/101876907-e1d60e80-3b95-11eb-9923-ef3f617bd278.png">

2020-12-11 11:31 UTC, inikolova approved these changes

2020-12-11 11:31 UTC, inikolova commented
Great job :)

2020-12-11 12:14 UTC, merged