fix: add generic spacer styles
telerik/kendo-themes pull request #2129
Opened 2020-12-09 16:11 UTC by inikolova

I am adding this class / style so we could avoid repetition of styles in different components.

2020-12-09 16:41 UTC, PreslavKozovski requested changes
Do not forget to add this util class to other themes :)

2020-12-10 07:57 UTC, joneff approved these changes

2020-12-10 07:57 UTC, joneff commented
Note: in the future we'll also add sized spacers

2020-12-10 08:03 UTC, silviyaboteva requested changes

2020-12-10 08:03 UTC, silviyaboteva commented on packages/classic/scss/utils/_spacer.scss
> +@import "~@progress/kendo-theme-default/scss/utils/_spacing.scss";
Change to `_spacer.scss` instead.

2020-12-10 08:20 UTC, PreslavKozovski approved these changes

2020-12-10 09:07 UTC, silviyaboteva approved these changes

2020-12-10 09:24 UTC, merged