fix: vertically center checkbox in grid cell
telerik/kendo-themes pull request #2146
Opened 2020-12-15 07:57 UTC by inikolova

2020-12-16 11:31 UTC, PreslavKozovski requested changes
The below comment is applicable to most of the `$grid-cell-checkbox-margin-y` variables.

2020-12-16 11:31 UTC, PreslavKozovski commented on packages/bootstrap/scss/grid/_variables.scss
> +$grid-cell-checkbox-margin-y: calc( #{$cell-padding-y} - (#{$button-calc-size} - #{$line-height-em}) / 2 ) / 1.25  !default; // $grid-command-cell-padding-y / 1.25
This is not a valid value. Here, we are assuming that the `postcss-calc` will remove the `calc`, however, if any of these variables change, and the `calc` is not removed, we will have an invalid output of the CSS.

2020-12-18 07:34 UTC, PreslavKozovski approved these changes

2020-12-18 07:42 UTC, joneff commented
Due to upcoming changes in the buttons, this fix will not be relevant as it depends on variables related to the current state of the button. Converting to draft for the time being

2022-04-11 08:38 UTC, joneff commented
To align checkboxes correctly, we need a wrapper around them (`k-checkbox-wrap`). Then and only then we can align them correctly, be it top or center align.

2022-04-11 08:38 UTC, closed without merging