Expansion panel styles revision
telerik/kendo-themes pull request #2263
Opened 2021-01-29 15:41 UTC by inikolova

https://github.com/telerik/kendo-themes/issues/2249

2021-02-01 08:49 UTC, PreslavKozovski requested changes
The expander is internally used in the Grid col menu, the new styles are breaking it (as seen in the tests).

Also, we should review why the timeline tests are breaking.

2021-02-03 15:14 UTC, inikolova commented on packages/default/scss/expansion-panel/_layout.scss
> +    }
Yes, this is by design :) However, I have addressed the problem :)

2021-02-03 15:46 UTC, PreslavKozovski approved these changes

2021-02-05 10:09 UTC, joneff approved these changes
I much prefer this look over the old one. Splendid job!

2021-02-05 10:11 UTC, GeorgeGindev approved these changes

2021-02-05 10:12 UTC, silviyaboteva approved these changes

2021-02-05 10:27 UTC, merged