fix: long content in item body overflows
telerik/kendo-themes pull request #2275
Opened 2021-02-03 15:01 UTC by inikolova

By default, flex items have min-height: auto as initial value (https://drafts.csswg.org/css-flexbox/#min-size-auto). Therefore in scenarios when the content placed in the TileLayout item body component is higher than the wrapper, it overflows. Setting min-height to 0 will give users the opportunity to use vertical scroll for the long content.

2021-02-05 16:43 UTC, joneff approved these changes

2021-02-08 13:38 UTC, silviyaboteva requested changes
We already have `k-tilelayout-item-body` class applied to the React, jQuery and Angular component this way. Can we remove the dash between the tile and layout words in the class?

2021-02-08 15:25 UTC, inikolova commented
Good catch, @silviyaboteva :)

2021-02-09 07:04 UTC, Juveniel approved these changes

2021-02-09 11:36 UTC, silviyaboteva approved these changes

2021-02-11 19:56 UTC, merged