Skeleton (New Component) - Overview Demo Test
telerik/kendo-themes pull request #2405
Opened 2021-03-29 15:14 UTC by GeorgeGindev

2021-04-01 09:19 UTC, PreslavKozovski requested changes
Check the below comments.

Also, I believe we should support non-grid skeletons. Change/add the selectors so the following HTML provides a default width/height `rect` the desired animation:

```
div.k-skeleton-rect.k-skeleton-pulse
```

2021-04-01 09:19 UTC, PreslavKozovski commented on packages/default/scss/skeleton/_layout.scss
> +        grid-template-rows: repeat(10, 1em);
Hardcoding like this is not okay. I believe this should look like this:

```
$skeleton-grid-columns-count: 10 !default;
$skeleton-grid-columns-size: 1fr !default;

grid-template-columns: repeat($skeleton-grid-columns-count, $skeleton-grid-columns-size);
```

I understand why you did that - the `.k-skeleton-circle`, however, you can handle this scenario like the badge - 

https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/badge/_variables.scss#L23
https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/badge/_layout.scss#L48

2021-04-01 14:20 UTC, silviyaboteva reviewed
I agree with Presli's comments. More specifically, you need to expose all variables for the component and add styles for normal `k-skeleton`if we support a non-grid one.

Another thing that is very helpful is the API section in the description, where you can write which option will triger either class or a inline styling. For reference the BottomNavigation component: https://github.com/telerik/kendo-themes/issues/1949

2021-04-08 11:02 UTC, PreslavKozovski approved these changes

2021-04-08 13:15 UTC, silviyaboteva approved these changes

2021-04-09 06:19 UTC, joneff approved these changes

2021-04-09 06:20 UTC, merged