fix(panelbar): the arrow icons are not aligned correctly in IE
telerik/kendo-themes pull request #2472
Opened 2021-05-10 13:59 UTC by silviyaboteva

fixes https://github.com/telerik/kendo-themes/issues/2388

The fix is related to the CSS properties [margin-inline-start](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-start) and [margin-inline-end](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-end) that are not supported by IE.

2021-05-10 14:09 UTC, silviyaboteva commented
hm, I'm not sure why these screenshots are produced. They seem to add some missing borders and vertically align some arrows in the calendars.

2021-05-10 15:16 UTC, JoomFX approved these changes

2021-05-11 07:49 UTC, joneff requested changes
Use `.k-ie` to target IE.

We are close to removing IE support, so it will be much easier if our IE specific cases are targeted.

2021-05-11 14:27 UTC, Juveniel commented
@silviyaboteva just a suggestion - for simplicity and better separation we can create a module for the legacy styles (e.g. compatibility) [like here](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/taskboard/_layout.scss#L221-L223) for example.

2021-05-17 11:45 UTC, joneff approved these changes

2021-05-17 11:46 UTC, merged