fix(colorpicker): wrong rtl style in color-gradient
telerik/kendo-themes pull request #2568
Opened 2021-06-21 15:03 UTC by PaskalevStoyan

fixes https://github.com/telerik/kendo-themes/issues/2560

2021-06-22 06:50 UTC, JoomFX approved these changes

2021-06-22 08:21 UTC, silviyaboteva requested changes
It is good practice to check other Kendo flavors for the same issue. In this case, only Angular reproduces this issue. In KendoReact the RTL styles are applied correctly: https://stackblitz.com/edit/react-wcv2md-sbuybp?file=app%2Fmain.jsx

You can add a tag FW:Angular :)

2021-06-22 08:21 UTC, silviyaboteva commented on packages/default/scss/colorpicker/_layout.scss
> +        &[dir="rtl"] {
The `dir` attribute can also be set at the root of the page, not directly to the element with class `k-flatcolorpicker`. So, I suggest adding a third selector here:
```
.k-rtl &,
[dir="rtl"]&,
[dir="rtl"] & { ... }
```

For reference, check badge styles: https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/badge/_layout.scss#L157

2021-07-09 15:40 UTC, joneff approved these changes
As a note, the visual distortion comes from the fact that previously, there was a `k-rtl` class on the container and there isnt (because angular applies it via attribute).

2021-07-09 15:44 UTC, merged