docs(bootstrap): add statement about Bootstrap v5 support
telerik/kendo-themes pull request #2771
Opened 2021-09-10 08:53 UTC by silviyaboteva

Resolves: https://github.com/telerik/kendo-themes/issues/2730

//cc @nrch

2021-09-10 12:57 UTC, JoomFX commented on packages/bootstrap/docs/index.md
> +As of 4.40.0 version, the Kendo UI for Angular Bootstrap theme officially supports Bootstrap v5. More information about the migration process and changes could be found in [this issue in our kendo-th
> go to any of the KendoReact demos

I believe this should be "go to any of the "Kendo UI for Angular demos"

2021-09-10 12:59 UTC, JoomFX commented on packages/bootstrap/docs/index.md
> +Additionally, the Bootstrap theme exposes the older v3 and v4 appearances though theme swatches that could be found in [the kendo-themes GitHub repository](https://github.com/telerik/kendo-themes/tre
there is a typo in `through` :)

2021-09-10 13:00 UTC, JoomFX requested changes

2021-09-10 13:00 UTC, JoomFX commented on packages/bootstrap/docs/index.md
> +Additionally, the Bootstrap theme exposes the older v3 and v4 appearances though theme swatches that could be found in [the kendo-themes GitHub repository](https://github.com/telerik/kendo-themes/tre
again, a typo in `through` :)

2021-09-10 16:41 UTC, joneff commented
@silviyaboteva I've simplified the wording a bit and clarified that the theme does not support Bootstrap 5, but rather depends on it.

2021-09-13 06:21 UTC, silviyaboteva commented
@joneff @JoomFX can you double-check now?

2021-09-13 08:40 UTC, joneff approved these changes

2021-09-13 08:42 UTC, Xizario approved these changes
perfect

2021-09-13 08:43 UTC, merged