Add focus state styles for tab item
telerik/kendo-themes pull request #3264
Opened 2022-01-19 13:46 UTC by epetrow

Fixes: https://github.com/telerik/kendo-themes/issues/2928

2022-01-19 13:47 UTC, silviyaboteva approved these changes

2022-01-24 08:26 UTC, silviyaboteva requested changes
Please rename the commit according to the [Commit Message Guidelines](https://github.com/telerik/kendo-themes/wiki/Commit-Message-Guidelines) with type and scope.

2022-01-24 08:40 UTC, silviyaboteva approved these changes

2022-01-24 10:37 UTC, joneff approved these changes

2022-01-24 10:37 UTC, merged