feat(datetimepicker, numerictextbox): add disabled state variables
telerik/kendo-themes pull request #3268
Opened 2022-01-21 08:58 UTC by epetrow

Related to: https://github.com/telerik/kendo-themes/issues/2887

2022-01-24 08:33 UTC, silviyaboteva approved these changes

2022-01-24 08:33 UTC, silviyaboteva commented on packages/default/scss/datetimepicker/_theme.scss
> +        &.k-state-disabled,
As of v5, we've switched from `k-state-*` to more generic  `k-*`. You've noticed that in some modules there are still selectors with `k-state-*` class. But they will be updated in the R2 2022 effort. 

In this PR we work with numeric and datetimepicker that was part of the v5 effort for R1 2022. So the `&.k-state-disabled` selector have to be removed.

2022-01-24 09:09 UTC, joneff requested changes
those should be `$kendo-input-` and `$kendo-picker-` variables.

2022-01-25 08:05 UTC, joneff approved these changes

2022-01-25 08:22 UTC, merged