Add padding when TextArea is used through directive in Angular
telerik/kendo-themes pull request #3404
Opened 2022-02-22 08:41 UTC by PaskalevStoyan

In Angular when the TextArea is used through a directive it doesn't have initial padding, thus the text resulting to be stuck in the borders of the box. This is because when used through the directive, the HTML is only a <textarea> element without a wrapper.

2022-02-22 09:12 UTC, JoomFX approved these changes

2022-02-25 05:32 UTC, joneff requested changes

2022-02-25 05:32 UTC, joneff commented on packages/default/scss/input/_layout.scss
> +
there is trailing space on this line, which means you don't have the correct setup. go to develop, pull and run `npm run setup`. after that, rebase this branch and fix the lint errors.

2022-03-11 06:16 UTC, joneff approved these changes

2022-03-11 06:31 UTC, merged