fix(floating-label): allow label to be clickable in order to focus as…
telerik/kendo-themes pull request #3429
Opened 2022-03-01 09:49 UTC by epetrow

…sociated input

Fixes: https://github.com/telerik/kendo-themes/issues/3421

2022-03-02 06:51 UTC, Juveniel requested changes

2022-03-02 06:51 UTC, Juveniel commented on packages/default/scss/floating-label/_layout.scss
> +                    pointer-events: none;
This is redundant, as the label will receive `pointer-events: none` from the `.k-state-empty > .k-label` selector on lines 40-45. Thus, this line can be removed.

2022-03-02 08:15 UTC, Juveniel approved these changes

2022-03-02 10:56 UTC, PaskalevStoyan approved these changes

2022-03-11 06:39 UTC, joneff approved these changes

2022-03-11 06:44 UTC, merged