fix(slider): add React specific styles for slider layout
telerik/kendo-themes pull request #3613
Opened 2022-05-19 13:20 UTC by kikostadinov

React issue:
https://github.com/telerik/kendo-react/issues/1301

2022-05-30 11:42 UTC, TeyaVes commented
@kikostadinov I don't think that using attributes as selectors is what we want. We should rather add a class and use it for adding the specific styles. In this way we would be able to add a visual test for the following functionality and add it easily in the rest of the Kendo suites if needed. In the general case, we add product-specific styles only where this cannot be avoided.

2022-05-30 11:53 UTC, kikostadinov commented
Add a visual test once https://github.com/telerik/kendo-themes/pull/3557 is merged.

2022-05-31 08:54 UTC, TeyaVes requested changes

2022-06-01 10:33 UTC, TeyaVes requested changes

2022-06-01 10:33 UTC, TeyaVes commented on packages/html/src/slider/tests/slider-tick-absolute-position.html
> +    <title>Button Size</title>
Change title here

2022-06-01 10:37 UTC, TeyaVes commented on packages/html/src/slider/tests/slider-tick-absolute-position.tsx
> +                    <Button icon="arrow-w" rounded="full" className="k-button-decrease"></Button>
change icons in vertical slider to arrow-n and arrow-s

2022-06-01 10:39 UTC, TeyaVes commented on packages/html/src/slider/tests/slider-tick-absolute-position.tsx
> +                            <a href="#" className="k-draghandle k-draghandle-end" style={{ left: '33%' }}></a>
Check whether the drag handle needs z-index as well, cause right now it's displayed under the ticks. It should be over them.

2022-06-03 11:15 UTC, TeyaVes approved these changes
You can now squash the commits into one, just make sure to drop the visual previews commits- a new one will be automatically generated after the push

2022-06-06 11:37 UTC, joneff approved these changes

2022-06-06 11:37 UTC, merged