[Fluent] Appbar
telerik/kendo-themes pull request #3766
Opened 2022-08-03 13:42 UTC by kikostadinov

Related to: https://github.com/telerik/kendo-themes-private/issues/3

2022-08-08 05:48 UTC, Juveniel requested changes

2022-08-08 05:48 UTC, Juveniel commented on packages/fluent/scss/appbar/_layout.scss
> +        margin-inline: var(--kendo-appbar-margin-x, #{$kendo-appbar-margin-x});
Add bracket spacing to all variables:

```suggestion
        margin-inline: var( --kendo-appbar-margin-x, #{$kendo-appbar-margin-x} );
```

2022-08-08 05:48 UTC, Juveniel commented on packages/fluent/scss/appbar/_layout.scss
> +        gap: var(--kendo-appbar-gap, #{$kendo-appbar-gap});
rename to `$kendo-appbar-spacing`

2022-08-08 05:48 UTC, Juveniel commented on packages/fluent/scss/appbar/_variables.scss
> +$kendo-appbar-font-size: $kendo-font-size !default;
use the --kendo-font-size var:

```suggestion
$kendo-appbar-font-size: var( --kendo-font-size, inherit )!default;
```

2022-08-08 05:48 UTC, Juveniel commented on packages/fluent/scss/core/_variables.scss
> +$kendo-line-height-em: calc( #{$kendo-line-height} * 1em) !default;
These variables are already defined. Rebase the branch with the latest changes from `develop`.

2022-08-10 11:05 UTC, TeyaVes commented on packages/fluent/scss/appbar/_variables.scss
> +        )
shouldn't we use the $kendo-appbar-primary-colors  as a second parameter for the map-merge instead of defining a new map here?

2022-08-10 12:01 UTC, Juveniel approved these changes

2022-08-10 12:02 UTC, merged