[Fluent] Notification
telerik/kendo-themes pull request #3769
Opened 2022-08-03 15:03 UTC by kikostadinov

Related to: https://github.com/telerik/kendo-themes-private/issues/3

2022-08-04 07:28 UTC, Juveniel requested changes

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/core/functions/_index.scss
>  // @forward "misc";
We could probably remove this import, as well as the empty `_colors` module

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_layout.scss
> +        margin-block: math.div($kendo-notification-padding-y, 2);
use `calc()` instead and remove the `sass:math` ref

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_theme.scss
> +        box-shadow: var(--INTERNAL--kendo-notification-shadow, var(--kendo-notification-shadow, #{$kendo-notification-shadow}));
From the design file it seems that there is no shadow for the Fluent Notification. Could you please double check this ?

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_variables.scss
> +$error: #FDE7E9;
Only use colors defined in the color system. I would suggest extending the [default `$kendo-theme-colors` map](https://github.com/telerik/kendo-themes/blob/develop/packages/fluent/scss/core/color-system/_theme.scss#L67).

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_variables.scss
> +$kendo-fluent-status-colors: (
Naming too generic, we can use `$kendo-notification-theme-colors` here.

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_variables.scss
> +$kendo-notification-padding-x: map-get($kendo-spacing, 2) !default;
add spacing

```suggestion
$kendo-notification-padding-x: map-get( $kendo-spacing, 2 ) !default;
```

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_variables.scss
> +$kendo-notification-padding-y: map-get($kendo-spacing, 1 ) !default;
add spacing

```suggestion
$kendo-notification-padding-y: map-get( $kendo-spacing, 1 ) !default;
```

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_variables.scss
> +$kendo-notification-border-radius: 2px; // $kendo-border-radius-md  !default;
use the global variable

```suggestion
$kendo-notification-border-radius:  var( --kendo-border-radius-md )
```

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_variables.scss
> +$kendo-notification-shadow: null !default; //$popup-shadow  !default;
Remove variable if not needed ( check design )

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_variables.scss
> +$kendo-notification-font-family: $kendo-font-family  !default;
```suggestion
$kendo-notification-font-family: var( --kendo-font-family, inherit) !default;
```

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_variables.scss
> +$kendo-notification-font-size: 14px; //$kendo-font-size-sm  !default;
```suggestion
$kendo-notification-font-size: var( --kendo-font-size, inherit ) !default;
```

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_variables.scss
> +$kendo-notification-line-height: calc(20 / 14); //$kendo-line-height  !default;
```suggestion
$kendo-notification-line-height: var( --kendo-line-height, normal ) !default;
```

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_variables.scss
> +$kendo-notification-icon-offset: 2px !default;
get value from `$kendo-spacing`

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/_variables.scss
> +$kendo-notification-icon-spacing: 4px !default; //$kendo-icon-spacing  !default;
get value from $kendo-spacing

2022-08-04 07:28 UTC, Juveniel commented on packages/fluent/scss/notification/index.scss
> +        "icons"
add "popup" as a dependency for the component

2022-08-05 14:53 UTC, Juveniel approved these changes

2022-08-08 10:05 UTC, TeyaVes approved these changes

2022-08-08 10:12 UTC, merged