[Fluent] Add tabstrip styles
telerik/kendo-themes pull request #3835
Opened 2022-08-15 13:42 UTC by epetrow

Related to: https://github.com/telerik/kendo-themes-private/issues/3

2022-08-19 12:54 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_variables.scss
> +$kendo-tabstrip-content-padding-x: map-get( $kendo-spacing, 2 ) !default;
According to the design this should be 12px (`map-get( $kendo-spacing, 2 )`)

2022-08-19 12:56 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_variables.scss
> +$kendo-tabstrip-content-padding-y: map-get( $kendo-spacing, 3 ) !default;
According to the design this should be 6px (`map-get( $kendo-spacing, 1 ) + map-get( $kendo-spacing, thin )`)

2022-08-19 13:04 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_layout.scss
> +        &.k-state-active,
Delete the `&.k-state-active` selector.

2022-08-19 13:05 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_layout.scss
> +            .k-item.k-state-active::after,
Delete the `.k-item.k-state-active::after` selector.

2022-08-19 13:08 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_theme.scss
> +
Either remove this empty line or add an empty line after line 103 😊

2022-08-19 13:14 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_variables.scss
> +$kendo-tabstrip-item-hovered-bg: get-theme-color-var( neutral-20 ) !default;
Use the CSS variable (`var( --kendo-hover-bg, inherit )`)

2022-08-19 13:14 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_variables.scss
> +$kendo-tabstrip-item-hovered-text: get-theme-color-var( neutral-190 ) !default;
Use the CSS variable (`var( --kendo-hover-text, inherit )`)

2022-08-19 13:22 UTC, JoomFX requested changes

2022-08-19 13:22 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_variables.scss
> +$kendo-tabstrip-item-hovered-border: get-theme-color-var( neutral-20 ) !default;
Use the CSS variable (`var( --kendo-hover-bg, inherit )`)

2022-08-19 13:22 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_variables.scss
> +$kendo-tabstrip-content-padding-y: map-get( $kendo-spacing, 3 ) !default;
According to the design this should be 6px (`map-get( $kendo-spacing, 1 ) + map-get( $kendo-spacing, thin )`)

2022-08-19 13:22 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_variables.scss
> +$kendo-tabstrip-content-padding-x: map-get( $kendo-spacing, 2 ) !default;
According to the design this should be 12px (`map-get( $kendo-spacing, 3 )`)

2022-08-19 13:22 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_variables.scss
> +$kendo-tabstrip-item-hovered-text: get-theme-color-var( neutral-190 ) !default;
Use the CSS variable (`var( --kendo-hover-text, inherit )`)

2022-08-19 13:22 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_variables.scss
> +$kendo-tabstrip-item-hovered-bg: get-theme-color-var( neutral-20 ) !default;
Use the CSS variable (`var( --kendo-hover-bg, inherit )`)

2022-08-19 13:22 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_theme.scss
> +
Either remove this empty line or add an empty line after line 103 😊

2022-08-19 13:22 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_layout.scss
> +            .k-item.k-state-active::after,
Delete the `.k-item.k-state-active::after` selector.

2022-08-19 13:22 UTC, JoomFX commented on packages/fluent/scss/tabstrip/_layout.scss
> +        &.k-state-active,
Delete the `&.k-state-active` selector.

2022-08-22 09:12 UTC, Juveniel approved these changes

2022-08-22 10:43 UTC, merged