[Fluent] Progressbar styles
telerik/kendo-themes pull request #3855
Opened 2022-08-22 07:47 UTC by kikostadinov

Related to: https://github.com/telerik/kendo-themes-private/issues/3

2022-08-23 07:30 UTC, TeyaVes requested changes

2022-08-23 07:30 UTC, TeyaVes commented on packages/fluent/scss/progressbar/_layout.scss
> +        @include border-radius( $kendo-progressbar-border-radius );
add CSS var

2022-08-23 07:30 UTC, TeyaVes commented on packages/fluent/scss/progressbar/_variables.scss
> +$kendo-progressbar-border: $kendo-progressbar-bg !default;
use the CSS variable here with a fallback to the Sass var:

var( --kendo-progressbar-bg, $kendo-progressbar-bg) 

In this way if anyone uses --kendo-progressbar-bg to override the bg color, it'll apply on the border as well.

The same goes for the rest of the sass vars used here

2022-08-23 10:07 UTC, Juveniel commented
@kikostadinov two tings:

I noticed that the circular progressbar has primary-190 stroke ? Is this the color showcased in the design or should it be the primary-130 ?

We need a test page for the ChunkProgressBar Buttons. Can you add a test page for this ?

2022-08-25 14:37 UTC, TeyaVes commented on packages/fluent/scss/progressbar/_layout.scss
> +            border-left-width: 3px;
do we need this rule since we have inline-start-width and it does the same?

2022-08-25 14:37 UTC, TeyaVes commented on packages/fluent/scss/progressbar/_layout.scss
> +            border-top-width: 3px;
do we need this rule since we have block-start-width and it does the same?

2022-08-25 14:37 UTC, TeyaVes commented on packages/fluent/scss/progressbar/_layout.scss
> +            border-inline-start-width: 3px;
I think we should rather assign a variable here instead of using 3px

2022-08-26 05:25 UTC, Juveniel approved these changes

2022-08-26 05:26 UTC, Juveniel commented
@kikostadinov after @TeyaVes reviews this, please merge commits in the first feat, re-gen images and rebase the branch with develop.

2022-08-26 12:12 UTC, TeyaVes approved these changes

2022-08-26 12:29 UTC, merged