[Fluent] Tilelayout
telerik/kendo-themes pull request #3857
Opened 2022-08-22 13:59 UTC by magdalenaan

2022-08-24 14:21 UTC, TeyaVes requested changes

2022-08-24 14:21 UTC, TeyaVes commented on packages/fluent/scss/tilelayout/_layout.scss
> +        border-width: var( --kendo-tilelayout-border-width, $kendo-tilelayout-border-width );
the fallback should be with an interpolation: #{$kendo-tilelayout-border-width}

the same goes for all vars

2022-08-24 14:21 UTC, TeyaVes commented on packages/fluent/scss/tilelayout/_theme.scss
> +        );
use CSS vars

2022-08-24 14:21 UTC, TeyaVes commented on packages/fluent/scss/tilelayout/_variables.scss
> +$kendo-tilelayout-hint-border: $kendo-component-border !default;
use CSS var as it's coming from the core file

2022-08-25 12:08 UTC, magdalenaan commented on packages/fluent/scss/tilelayout/_variables.scss
> +$kendo-tilelayout-card-border-width: $kendo-card-border-width !default;
The design is correct so there is a shadow instead of a border.

2022-08-26 12:03 UTC, TeyaVes approved these changes

2022-08-26 12:06 UTC, merged