fix(pivotgrid): add focus state
telerik/kendo-themes pull request #3887
Opened 2022-08-29 07:48 UTC by kikostadinov

Issue: https://github.com/telerik/kendo-themes/issues/3804

2022-08-30 08:54 UTC, TeyaVes requested changes

2022-08-30 08:54 UTC, TeyaVes commented on packages/default/scss/pivotgrid/_theme.scss
> +    .k-pivotgrid-empty-cell.k-state-focus,
let's delete the k-state-focus as we're about to remove all state selectors in the following PR: https://github.com/telerik/kendo-themes/pull/3877

2022-08-30 12:48 UTC, Juveniel requested changes
Add a test case for the empty cell focus state ( this could probably be achieved in one of the existing tests where states of cells are shown ).

2022-08-30 12:48 UTC, Juveniel commented on packages/default/scss/pivotgrid/_theme.scss
> +    .k-pivotgrid-cell:focus,
this is duplicated on line 62

2022-09-01 15:10 UTC, Juveniel approved these changes

2022-09-01 15:12 UTC, TeyaVes approved these changes

2022-09-01 15:12 UTC, merged