[Fluent] Map
telerik/kendo-themes pull request #3908
Opened 2022-09-01 11:48 UTC by kikostadinov

related to: https://github.com/telerik/kendo-themes-private/issues/3

2022-09-01 12:27 UTC, Juveniel requested changes

2022-09-01 12:27 UTC, Juveniel commented on packages/fluent/scss/map/_layout.scss
> +        height: var( --$kendo-map-height, #{$kendo-map-height} );
```suggestion
height: var( --kendo-map-height, #{$kendo-map-height} );
```

2022-09-01 12:27 UTC, Juveniel commented on packages/fluent/scss/map/_variables.scss
> +$kendo-map-attribution-font-size: calc($kendo-map-font-size * .75) !default;
spacing

2022-09-01 12:27 UTC, Juveniel commented on packages/utils/scss/layout/_position.scss
> +    }
you can remove the rtl parts:

```suggestion
.#{$kendo-prefix}top-start,
.#{$kendo-prefix}pos-top-start {
    inset-block-start: 0;
    inset-inline-start: 0;
}
```

2022-09-01 12:27 UTC, Juveniel commented on packages/utils/scss/layout/_position.scss
> +/// @group position
no needs of docs for these, as we will deprecate them in favor of the above-generated map at some point after the release, thus please remove these

2022-09-01 12:27 UTC, Juveniel commented on packages/utils/scss/layout/_position.scss
> +/// @group position
same for these

2022-09-01 12:27 UTC, Juveniel commented on packages/utils/scss/layout/_position.scss
> +    .k-pos-#{$side} { #{$side}: 0; } // sass-lint:disable-line brace-style
use .#{$kendo-prefix}

2022-09-02 07:17 UTC, TeyaVes requested changes

2022-09-02 07:17 UTC, TeyaVes commented on packages/fluent/scss/map/_variables.scss
> +$kendo-map-navigator-width: calc( #{$kendo-icon-size * 3} + #{$kendo-map-navigator-padding * 2} ) !default;
use the CSS var for the icon-size exposed in the root

2022-09-02 07:17 UTC, TeyaVes commented on packages/fluent/scss/map/_variables.scss
> +@use "../icon/_variables.scss" as *;
no need for this if the CSS vars for the icons are used

2022-09-02 07:17 UTC, TeyaVes commented on packages/fluent/scss/map/images/markers.scss
> +    @include register-data-uri("markers.png", "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAABQCAYAAAAKlxWDAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA35JREFUeNrsWF1IVEEUPu7amhKUmqUUkh
remove this image as we don't seem to use it anymore

2022-09-02 13:52 UTC, Juveniel approved these changes

2022-09-02 13:53 UTC, merged