Fluent fixes
telerik/kendo-themes pull request #3934
Opened 2022-09-09 06:12 UTC by kikostadinov

Related to: https://github.com/telerik/kendo-themes-private/issues/26

Wizard
- `Paddings of .k-wizard-buttons should be like .k-wizard-content. Currently, .k-wizard-buttons haven't paddings and 'Steps' text doesn't seem properly aligned to the content.`

Stepper
- `The background color of the current item should be #005A9E by design`
- `Disabled state of 'default' step(not 'done' ) doesn't follow the design - there is not visual indication that the step is disabled`

Splitter
- `bg color of the focused item should be blue - currently it's grey`

ChunkProgressBar
- `The space between the chunks should be 1px, not 3 px.`

2022-09-09 13:38 UTC, Juveniel requested changes

2022-09-09 13:38 UTC, Juveniel commented on packages/fluent/scss/wizard/_layout.scss
> -            padding-block: var( --kendo-wizard-content-padding-y, #{$kendo-wizard-content-padding-x} );
either set the variables to 0px and allow the option for customization or remove both the _layout styles and the variables as well.

2022-09-09 13:38 UTC, Juveniel commented on packages/fluent/scss/stepper/_layout.scss
> +            font-weight: 600;
extract a variable that uses the --kendo-font-weight-bold var

2022-09-09 13:38 UTC, Juveniel commented on packages/fluent/scss/stepper/_layout.scss
> +            }
probably this ?

```suggestion
.k-step-label {
   font-weight: normal;
}
```

2022-09-12 06:06 UTC, PaskalevStoyan submitted a review, later dismissed

2022-09-12 06:06 UTC, PaskalevStoyan commented on packages/fluent/scss/splitter/_variables.scss
> +$kendo-splitbar-selected-text: $white !default;
use `var( --kendo-component-bg, inherit )` here

2022-09-12 06:09 UTC, Juveniel commented
all commits should be fix(componentName): scenario in fluent theme, as the theme is already released

2022-09-12 06:44 UTC, Juveniel requested changes

2022-09-12 06:44 UTC, Juveniel commented on packages/fluent/scss/stepper/_layout.scss
> +            font-weight: var( --kendo-stepper-current-label-font-weight, #{$kendo-stepper-current-label-font-weight} );;
remove second semicolon

2022-09-12 07:17 UTC, Juveniel approved these changes

2022-09-12 07:27 UTC, merged