Fluent fixes 9
telerik/kendo-themes pull request #3988
Opened 2022-09-21 14:42 UTC by kikostadinov

Related to: https://github.com/telerik/kendo-themes-private/issues/26

SplitButton
- The ddl arrow does not gets correct background color on hover in Flat mode and Base theme color

2022-09-29 12:57 UTC, TeyaVes requested changes

2022-09-29 12:57 UTC, TeyaVes commented on packages/fluent/scss/bottom-navigation/_variables.scss
> -$kendo-bottom-nav-item-min-height: calc( var( --kendo-icon-size, 1rem ) + #{$kendo-padding-x * 2} - #{$kendo-bottom-nav-padding-x * 2} ) !default;
the min-height should be related to the icon size. I would suggest replacing kendo-spacing 6 with $kendo-bottom-nav-item-icon-size var that you have defined above

2022-09-29 12:57 UTC, TeyaVes commented on packages/fluent/scss/split-button/_layout.scss
> +        &.k-button-sm {
I would suggest creating a map for this and defining the sizes in the variables file (similar to the sizes in the button). In this way it'll be easier if we add different button sizes in the future.

2022-09-29 12:57 UTC, TeyaVes commented on packages/fluent/scss/split-button/_variables.scss
> +$kendo-split-button-arrow-delimiter-offset-sm: $kendo-split-button-arrow-padding-x-sm !default;
do we need these extra variables here?

2022-09-30 11:06 UTC, TeyaVes approved these changes

2022-09-30 11:33 UTC, Juveniel requested changes

2022-09-30 11:33 UTC, Juveniel commented on packages/fluent/scss/bottom-navigation/_variables.scss
> +$kendo-bottom-nav-item-min-height: calc( $kendo-bottom-nav-item-icon-size + $kendo-bottom-nav-item-icon-size + ($kendo-bottom-nav-item-padding-y * 2) ) !default;
use interpolation here, otherwise this will generate invalid styles

2022-09-30 12:07 UTC, Juveniel approved these changes

2022-09-30 13:10 UTC, merged