fix: gauge track is not visible
telerik/kendo-themes pull request #3998
Opened 2022-09-26 12:05 UTC by PaskalevStoyan

related to: https://github.com/telerik/kendo-themes/issues/3997

2022-09-26 12:19 UTC, epetrow commented
@PaskalevStoyan I noticed that the gauge pointer color is also incorrect, do you mind changing it as well?

2022-09-26 14:00 UTC, epetrow approved these changes

2022-09-26 14:26 UTC, Juveniel requested changes
Two things:

1) Fix the commit message e.g `fix(gauge): pointer and track have no color in fluent theme`

2) Add milestone to the issue

Note: if you want the related item to be closed automatically when this PR is merged you can use `fixes: #issue` instead of `related to: #issue`

2022-09-27 06:20 UTC, Juveniel commented
@PaskalevStoyan there is a modified test in the `/tests` folder. We should refrain from modifying those, as they are automatically generated ( CI ).

2022-09-27 08:29 UTC, Juveniel approved these changes

2022-09-27 08:30 UTC, merged