feat: add TimeDurationPicker component
telerik/kendo-themes pull request #4042
Opened 2022-10-11 14:43 UTC by magdalenaan

related https://github.com/telerik/kendo-themes-private/issues/12

2022-10-12 12:40 UTC, magdalenaan commented
The TimeDurationPicker icon will be changed when we have updated the font file.

2022-10-13 07:44 UTC, TeyaVes submitted a review, later dismissed
a couple of things that I noticed:

- the Fluent styles are missing
- the adaptive timepicker tests are now empty. It seems that with the changes in the timeselector html helper they got broken
- the paddings of the titles (the current time on the left side of the Now button) are missing and the text goes further to the left, which I don't think is by design

2022-10-13 07:44 UTC, TeyaVes commented on packages/bootstrap/scss/timeselector/_variables.scss
> +$time-selector-header-padding-x: map-get( $spacing, 4 ) !default;
from this PR on we should use k-map-get instead of map-get: https://github.com/telerik/kendo-themes/pull/4030/files

2022-10-13 07:44 UTC, TeyaVes commented on packages/bootstrap/scss/timedurationpicker/_index.scss
> +
shall we add dependency to the icons as well?

2022-10-13 07:44 UTC, TeyaVes commented on packages/html/src/timedurationpicker/tests/timedurationpicker.tsx
> +                <span className="k-timepicker k-timedurationpicker k-input k-input-md k-rounded-md k-input-solid">
why don't we use the timepicker html helper here?

2022-10-13 14:35 UTC, magdalenaan commented
The Fluent theme will be added after approving this PR, so the developer could start working on the widget.

2022-10-13 15:48 UTC, magdalenaan commented
> * the paddings of the titles (the current time on the left side of the Now button) are missing and the text goes further to the left, which I don't think is by design
There are inconsistencies between paddings in the TimePicker and TimeDurationPicker popup headers in the design. I will discuss it with the designer and will fix them after final design is provided.

2022-10-14 06:58 UTC, Juveniel requested changes

2022-10-14 06:58 UTC, Juveniel commented on packages/default/scss/timeselector/_layout.scss
> +        }
these are not needed ( see previous comment )

2022-10-14 06:58 UTC, Juveniel commented on packages/html/src/timedurationpicker/tests/timedurationpicker-expanded.tsx
> +                </span>
Use component here:

```html
<TimeDurationPicker />
```

2022-10-14 06:58 UTC, Juveniel commented on packages/html/src/timedurationpicker/tests/timedurationpicker.tsx
> +                <TimePicker placeholder="TimePicker..." />
We should not use `<TimePicker />` here, we should use `<TimeDurationPicker />`

This is applicable for all test cases in this test file.

2022-10-14 06:58 UTC, Juveniel commented on packages/html/src/timedurationpicker/tests/timedurationpicker.tsx
> +import { TimePicker } from '../../timepicker';
```suggestion
import { TimeDurationPicker } from '../../timedurationpicker';
```

2022-10-14 06:58 UTC, Juveniel commented on packages/html/src/timedurationpicker/tests/timedurationpicker.tsx
> +                <TimePicker placeholder="02 days : 01 hours : 30 mins" />
We should use `<TimeDurationPicker />` here. This is applicable for all test cases in this test file.

2022-10-14 06:58 UTC, Juveniel commented on packages/html/src/timepicker/timepicker.tsx
> +    icon?: 'clock' | 'arrow-clock';
the icon could be any icon, thus this should be a string

2022-10-14 07:26 UTC, TeyaVes commented on packages/fluent/scss/timedurationpicker/index.scss
> +        "popup",
add dependency to icon package. This should be done in the default and classic themes as well

2022-10-14 07:55 UTC, magdalenaan commented on packages/html/src/time-selector/time-selector-header.tsx
> +            columns
The columns prop is used for resolving the currentTime const.

2022-10-17 16:17 UTC, joneff approved these changes

2022-10-17 16:25 UTC, merged