Upload unified rendering
telerik/kendo-themes pull request #4076
Opened 2022-10-31 15:10 UTC by TeyaVes

closes: https://github.com/telerik/kendo-themes-private/issues/48

2022-11-04 13:28 UTC, TeyaVes commented
@telerik/kendo-a11y , can you please review the suggested updates on the upload rendering

2022-11-07 09:53 UTC, epetrow commented
Just one comment from me, do we need to use `{...htmlAttributes}` in the helpers upload-dropzone, upload-file and upload?

2022-11-10 07:27 UTC, veselints approved these changes

2022-11-10 14:56 UTC, TeyaVes commented
> Just two things that I noticed:
> 
> * Do we need to use `{...htmlAttributes}` in the helpers upload-dropzone, upload-file and upload?
> * The color of the close buttons has changed, is that intended?

I've removed the `{...htmlAttributes}` from where it wasn't needed;
The flat buttons changed color as they are no longer in a `k-upload-status` container. This has been synced with the design team.

2022-11-14 13:40 UTC, epetrow approved these changes

2022-11-16 08:32 UTC, Juveniel reviewed
I noticed that in the classic theme, the bottom border of the button is not visible. Could you take a look ?

![image](https://user-images.githubusercontent.com/16972160/202128492-412fa48d-336e-46d1-9f17-f7cd9fd0e6eb.png)
 
 One additional thing - the dropzone text in [the pdf viewer test](tests/_output/bootstrap/pdf-viewer/pdf-viewer-blank-page.png) does not seem centered.

2022-11-16 08:32 UTC, Juveniel commented on packages/html/src/upload/upload-file.tsx
> +    fileState?: 'uploaded' | 'uploading';
do we need the file prefix here ? As we are already in the UploadFile context, we can use name, size, etc.

2022-11-17 13:07 UTC, TeyaVes commented
> I noticed that in the classic theme, the bottom border of the button is not visible. Could you take a look ?
> 
> ![image](https://user-images.githubusercontent.com/16972160/202128492-412fa48d-336e-46d1-9f17-f7cd9fd0e6eb.png)
> 
> One additional thing - the dropzone text in [the pdf viewer test](tests/_output/bootstrap/pdf-viewer/pdf-viewer-blank-page.png) does not seem centered.

The border in the Classic theme is cut out only in the image. I tested it on Mozilla and Chrome and the bottom border is visible in both cases.

2022-11-18 09:11 UTC, joneff requested changes
Few changes to address

2022-11-18 09:11 UTC, joneff commented on packages/default/scss/upload/_layout.scss
>          .k-progressbar {
If you need to, sync with Emo about the progressbar. If needed add a css variable that sets the height of the progressbar.

2022-11-18 09:11 UTC, joneff commented on packages/default/scss/upload/_layout.scss
>              .k-progress {
This should probably be removed. We should not customize such styles.

2022-11-18 09:11 UTC, joneff commented on packages/default/scss/upload/_layout.scss
>                  text-align: left;
we can use logical text align.

2022-11-18 09:11 UTC, joneff commented on packages/default/scss/upload/_layout.scss
>                  .k-upload-status > .k-icon {
we can use logical margin

2022-11-18 09:11 UTC, joneff commented on packages/default/scss/upload/_theme.scss
> +        .k-multiple-files-wrapper .kk-file-summary {
```suggestion
        .k-multiple-files-wrapper .k-file-summary {
```

double kk in selector.

2022-11-30 11:45 UTC, Juveniel approved these changes

2022-12-13 08:55 UTC, Raisolution commented
> k-file-invalid class is replaced with k-file-error

There is a difference between those two classes. The first one refers to a file that has failed the set restrictions and will not be uploaded at all, while the second one refers to a file which was attempted for upload, but the upload process failed. I am not sure if the two classes attach different styling, but `k-file-invalid` should stay as is, as it has different meaning for the Upload users.

2022-12-13 13:34 UTC, TeyaVes commented
> > k-file-invalid class is replaced with k-file-error
> 
> There is a difference between those two classes. The first one refers to a file that has failed the set restrictions and will not be uploaded at all, while the second one refers to a file which was attempted for upload, but the upload process failed. I am not sure if the two classes attach different styling, but `k-file-invalid` should stay as is, as it has different meaning for the Upload users.

We've decided to keep the `k-file-invalid` class along with the `k-file-error` class. The themes will use the `k-file-error` class for styling, but we are keeping the `k-file-invalid` class if the clients need to differentiate between the two

2022-12-14 13:53 UTC, joneff approved these changes

2022-12-14 13:54 UTC, merged