Unify rendering Loader
telerik/kendo-themes pull request #4082
Opened 2022-11-01 11:10 UTC by kikostadinov

Related to: https://github.com/telerik/kendo-themes-private/issues/54

### Rendering

<details>

<summary> Universal </summary>

```html

<div class="k-loader k-loader-pulsing-2 k-loader-primary k-loader-lg">
	<div class="k-loader-canvas">
		<span class="k-loader-segment"></span>
		<span class="k-loader-segment"></span>
	</div>
</div>
```
</details>

### Changes

- Remove the `k-widge`t class in jQuery
- Remove the `telerik-blazor` class in Blazor

### Visual Tests

Link related visual tests here from the `/tests/` folder.

## Deliverables

- [ ] Universal rendering
- [ ] HTML Component
- [ ] HTML JSON Spec
- [ ] Rename variables to `$kendo-[varName]`
- [ ] Update tests

2022-11-03 08:22 UTC, TeyaVes commented on packages/html-spec/src/loader/loader.json
> +                            ".k-loader-{options.themeColor}"
replace options.themeColor with the actual themeColor here for each value: k-loader-base, k-loader-primary, etc.

2022-11-03 08:22 UTC, TeyaVes commented on packages/html-spec/src/loader/loader.json
> +[
I believe we should add json for the loader-container as well

2022-11-10 15:35 UTC, TeyaVes commented
@kikostadinov , is the loader -lg by default? This is what I see in the reference rendering, but in the demos it seems that it's -md

2022-11-11 06:37 UTC, Juveniel submitted a review, later dismissed

2022-11-11 06:37 UTC, Juveniel commented on packages/html-spec/src/loader/loader.json
> +                "name": "animationEffect",
```suggestion
"name": "animation",
```

2022-11-11 06:37 UTC, Juveniel commented on packages/html/src/loader/loader-container.tsx
> +    labelThemeColor?: null | 'base' | 'primary' | 'secondary' | 'tertiary' | 'info' | 'success' | 'warning' | 'error' | 'dark' | 'light' | 'inverse';
use `themeColor` for the prop name

2022-11-11 06:37 UTC, Juveniel commented on packages/html/src/loader/loader-container.tsx
> +    loaderAnimationEffect?: 'pulsing-2' | 'spinner-3' | 'spinner-4';
use `animation` for the prop name

2022-11-11 06:37 UTC, Juveniel commented on packages/html/src/loader/loader-container.tsx
> +    hasPanel?: boolean
use `panel` for the prop name

2022-11-11 06:37 UTC, Juveniel commented on packages/html/src/loader/loader-container.tsx
> +    overlayColor?: 'dark' | 'light';
use `overlay` fro the prop name

2022-11-11 06:37 UTC, Juveniel commented on packages/html/src/loader/loader.tsx
> +    loaderAnimationEffect?: 'pulsing-2' | 'spinner-3' | 'spinner-4';
use `animation` here also

2022-11-11 06:37 UTC, Juveniel commented on tests/loader/loader-container-colors.html
> +                    <div class="k-loader k-loader-pulsing-2 k-loader-lg k-loader-primary">
you could reverse the order of the `size` and `themeColor` props in the component definition to avoid re-generating the tests

2022-11-14 14:55 UTC, epetrow requested changes

2022-11-14 14:55 UTC, epetrow commented on packages/html-spec/src/loader/loader-container.json
> +        "component": "loader",
Shouldn't this be `"component": "loader-container"` ?

2022-11-14 14:55 UTC, epetrow commented on packages/html-spec/src/loader/index.js
> +const componentJson = require('./loader.json');
```suggestion
// We should require and export loader-container as well.

const loaderJson = require('./loader.json');
const loaderContainerJson = require('./loader-container.json')

exports.loader = [ loaderJson, loaderConteinerJson ];
```

2022-11-14 15:00 UTC, epetrow commented on packages/html-spec/src/loader/index.js
> +const componentJson = require('./loader.json');
Also we should comply with the JSON schema outlined in this PR https://github.com/telerik/kendo-themes/pull/4069

2022-11-25 15:06 UTC, epetrow commented
@kikostadinov Please rename your commit test(loader): add html components to > feat(html): add loader html helper and also update the renamed props in the Loader tests because they are broken now. e.g. `loaderAnimationEffect` > `animation`

2022-12-13 14:58 UTC, joneff approved these changes
For some reason the chip results are generated, but apart from that -- LGTM

2022-12-13 14:59 UTC, merged