Utils extend docs
telerik/kendo-themes pull request #4336
Opened 2023-03-10 13:33 UTC by magdalenaan

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/background/_background-clip.scss
> +/// This is equivalent to `padding: padding-box;`. The background extends to the outside edge of the border (but underneath the border in z-ordering).
`background-clip:` instead of `padding;` here

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/background/_background-clip.scss
> +/// This is equivalent to `content: content-box;`. The background extends to the outside edge of the border (but underneath the border in z-ordering).
`background-clip:` instead of `content:`

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/border/_outline-offset.scss
> +/// @name .k-outline
`.k-outline-1` since  we have `.k-outline` which sets `outline-width: 1px`?

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/flex-grid/_align-items.scss
> +/// This is equivalent to `align-items: selft-end;`. The items are packed flush to the edge of the alignment container's end side of the item, in the appropriate axis.
`self-end` here and below in the `@example`

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/flex-grid/_align-self.scss
> +/// This is equivalent to `align-self: first-baseline;`. Specifies participation in first baseline alignment: aligns the alignment baseline of the box's first baseline set with the corresponding base
`first baseline` instead of `first-baseline`

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/flex-grid/_align-self.scss
> +/// This is equivalent to `align-self: last-baseline;`. Specifies participation in last baseline alignment: aligns the alignment baseline of the box's first or last baseline set with the correspondin
`last baseline` instead of `last-baseline`

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/flex-grid/_gap.scss
> +/// This is equivalent to `gap: 1px;`. Sets zero 1px of gaps (gutters) between rows and columns.
Same goes here do we need both `.k-gap-1px` and `.k-gap-hair`?

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/flex-grid/_place-self.scss
> +/// @name .k-place-self-selft-start
`self-start`

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/flex-grid/_place-self.scss
> +/// @name .k-place-self-selft-start
`@name .k-place-self-flex-start`

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/flex-grid/_place-self.scss
> +/// @name .k-place-self-self-end
`@name .k-place-self-flex-end`

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/flex-grid/_place-items.scss
> +/// @name .k-place-items-selft-start
`@name .k-place-items-flex-start`

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/flex-grid/_place-items.scss
> +/// @name .k-place-items-selft-start
`self-start` here

2023-03-23 14:53 UTC, epetrow commented on packages/utils/scss/interactivity/_cursor.scss
> +/// @group cursor
missing @contextType css here

2023-03-28 14:32 UTC, magdalenaan commented
I keep removing descriptional docs in a separate commit - just in case.

2023-03-29 05:49 UTC, Juveniel commented
fixes: https://github.com/telerik/kendo-themes/issues/3561

2023-03-29 13:48 UTC, TeyaVes requested changes

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/flex-grid/_flex.scss
>  /// This is the same as `flex: initial;` and the shorthand for the default value: `flex: 0 1 auto`. It sizes the item based on its `width`/`height` properties (or its content if not set). It makes th
Shall we delete the above paragraph and replace it with This is equivalent to...

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/flex-grid/_justify-content.scss
> +/// @example justify-content: center;
the class is missing here:
/// @name .k-justify-content-center

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/flex-grid/_justify-items.scss
> +/// @example justify-items: center;
class is missing here

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/flex-grid/_justify-self.scss
> +/// @example justify-self: center;
class is missing here

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/flex-grid/_place-content.scss
> +/// @group place-content
class is missing here

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/flex-grid/_place-items.scss
> +/// @group place-items
missing class

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/flex-grid/_place-self.scss
> +/// @example place-self: center;
missing class

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/layout/_object-fit.scss
> +/// This is equivalent to `object-fit: scale-down;`.
missing class

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/layout/_placement.scss
> +/// @name .k-top-left-0
k-bottom-left-0

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/layout/_placement.scss
> +/// @name .k-top-left-0
k-top-right-0

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/layout/_placement.scss
> +/// @name .k-top-left-0
k-bottom-right-0

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/layout/_placement.scss
> +/// This is equivalent to `inset-inline: 0;`.
the whole code block is the same as the one above, I suppose it should be inset-block here

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/layout/_zindex.scss
> +/// This is equivalent to `z-index: 0;`.
the whole code nlock is the same as the one above, maybe k-zindex-1 here?

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/sizing/_height.scss
> +/// This is equivalent to `height: 100vh;`.
whole block same as the one above

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/sizing/_width.scss
> +/// @example width: 100vh;
same as the one above

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/transform/_origin.scss
> +/// @example transform-origin: center;
the class names in the whole file should be prefixed with k-, .k-origin-center

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/transform/_skew.scss
> +/// This is equivalent to `transform: skewY(1deg);`.
if we have skew-x-0, shouldn't we have skew-y-0 as well?

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/typography/_font-weight.scss
> +/// @example font-weight: 400;
the normal font weight shall be 400 and the light 300

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/typography/_list-style.scss
> +/// @example list-style-typ: none;
list-style-typE everywhere in the file

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/typography/_text-transform.scss
>  /// @name k-text-lowercase
. before the class name- .k-text-lowercase

2023-03-29 13:48 UTC, TeyaVes commented on packages/utils/scss/typography/_vertical-align.scss
> +/// This is equivalent to `text-align: left;`.
text-align: left is not vertical, but horizontal align, the whole file needs to be changed with vertical alignment

2023-04-03 07:52 UTC, TeyaVes commented on packages/utils/scss/sizing/_width.scss
> +/// This is equivalent to `min-width: 100vh;`.
shouldn't it be vw here instead of vh?

2023-04-03 10:40 UTC, TeyaVes approved these changes

2023-04-03 13:36 UTC, merged