feat(html): add forms helper
telerik/kendo-themes pull request #4353
Opened 2023-03-28 15:53 UTC by epetrow

part of: https://github.com/telerik/kendo-themes-private/issues/18

**_Note:_** The changes in the Fluent theme are expected and are related to the use of different classes on the label in the tests e.g. `k-label` and `k-form-label`

2023-04-05 15:36 UTC, TeyaVes approved these changes

2023-04-05 15:37 UTC, TeyaVes commented on packages/html/src/form/form-field.tsx
> +    disabled?: boolean;
we can add the disabled prop as a state here

2023-04-06 06:28 UTC, Juveniel requested changes

2023-04-06 06:28 UTC, Juveniel commented on tests/grid/grid-editing-popup.html
> +                                <div class="k-form-field-checkbox-wrapper">
we do not need  the div with class `k-form-field-checkbox-wrapper`

2023-04-06 06:28 UTC, Juveniel commented on tests/scheduler/scheduler-edit-dialog.html
> +                                <div class="k-form-field-checkbox-wrapper">
`<div class="k-form-field-checkbox-wrapper">` should be removed

2023-04-06 06:28 UTC, Juveniel commented on tests/scheduler/scheduler-edit-dialog.html
> +                                <div class="k-form-field-checkbox-wrapper">
`<div class="k-form-field-checkbox-wrapper">` should be removed

2023-04-06 06:28 UTC, Juveniel commented on packages/html/src/form/form-field.tsx
> +    alignText?: 'start' | 'end';
is `alignText` being used anywhere ? If not, please remove it.

2023-04-06 06:28 UTC, Juveniel commented on packages/html/src/form/form-field.tsx
> +                </ConditionalWrapper>
I am not sure we need those conditionals as:

1) The `k-form-field-wrap` can be rendered everytime
2) The checkbox conditional is not needed, as the `<Checkbox />` spec already adds its required wrapper.

2023-04-06 14:13 UTC, merged