Gantt popup editing
telerik/kendo-themes pull request #4368
Opened 2023-04-03 15:48 UTC by epetrow

2023-04-11 09:16 UTC, TeyaVes reviewed
And one more thing I noticed:
-the grid-editing popup is now add item popup, shall it be like this?

2023-04-11 09:16 UTC, TeyaVes commented on packages/html/src/scheduler/tests/scheduler-edit-dialog.tsx
> +                            <div className="k-label k-form-label">
why do we need the commented sections here?

2023-04-12 11:29 UTC, TeyaVes approved these changes

2023-04-13 10:04 UTC, Juveniel requested changes
LGTM, please address comments so we can proceed and merge this

2023-04-13 10:04 UTC, Juveniel commented on tests/scheduler/scheduler-edit-dialog.html
> -                                </div>
we need to have the reference for the recurrence editors as well, please bring them back

2023-04-13 11:34 UTC, epetrow commented on tests/editor/editor-image-editor.html
> +                    <div class="k-form k-form-md k-form-vertical">
Yes, according to the Design guidelines for the forms they should have vertical orientation.

2023-04-13 13:11 UTC, Juveniel commented
@epetrow, please verify also that the titles of the Gantt, Grid, TreeList and Scheduler edit/add popups matches the guidelines from [here](https://github.com/telerik/web-components-ux/issues/408#issuecomment-1327396271) e.g:
  *  For Grid and Treelist the titles are: "Add item" and "Edit item";
  *  For Gantt the titles are: "Add task" and "Edit task";
  *  For Scheduler the titles are: "Add event" and "Edit event".

2023-04-14 10:53 UTC, Juveniel approved these changes

2023-04-14 10:53 UTC, merged