Fix listbox overlapping
telerik/kendo-themes pull request #4766
Opened 2023-10-26 10:38 UTC by epetrow

fixes: https://github.com/telerik/kendo-themes/issues/4704

2023-10-27 08:07 UTC, inikolova approved these changes

2023-10-27 08:10 UTC, inikolova commented
In my opinion we should remove the following CSS rule from the test:
`.k-listbox .k-list-scroller {
   height: auto;
}`
and demonstrate how ListBox with default height acts.

2023-10-27 08:21 UTC, Juveniel requested changes
see previous comment

2023-10-27 08:40 UTC, inikolova commented
@Juveniel I agree that the best option is to adjust the scroller height internally.

2023-10-30 14:54 UTC, inikolova approved these changes

2023-11-06 08:06 UTC, JoomFX approved these changes

2023-11-06 08:55 UTC, merged