New Prompt Component
telerik/kendo-themes pull request #4824
Opened 2023-12-18 13:33 UTC by Juveniel

2023-12-18 15:51 UTC, epetrow requested changes

2023-12-18 15:51 UTC, epetrow commented on packages/bootstrap/scss/prompt/_variables.scss
> +/// The text color of the of the Prompt.
There are some redundant words in the variable description that should be omitted: 

The text color of the <ins>of the</ins>, The background color of the <ins>of the</ins>, The border color of the <ins>of the</ins>

_Note:_ This appears from line 3 through 26

2023-12-18 15:51 UTC, epetrow commented on packages/classic/scss/prompt/_variables.scss
> +/// The text color of the of the Prompt.
Same here, redundant use of:  <ins>of the</ins> lines 3 through 26

2023-12-18 15:51 UTC, epetrow commented on packages/default/scss/prompt/_variables.scss
> +/// The text color of the of the Prompt.
Here as well, line 3 through 26 -> remove extra <ins>of the</ins>

2023-12-18 15:51 UTC, epetrow commented on packages/fluent/scss/prompt/_layout.scss
> +        padding-block: var( --kendo-prompt-suggestion-padding-x, #{$kendo-prompt-suggestion-padding-y} );
Shouldn't it be `var( --kendo-prompt-suggestion-padding-y, ...` here?

2023-12-18 15:51 UTC, epetrow commented on packages/fluent/scss/prompt/_theme.scss
> +        @include fill(
Shouldn't we use `$kendo-prompt-header-*` here?

2023-12-18 15:51 UTC, epetrow commented on packages/fluent/scss/prompt/_variables.scss
> +/// The text color of the of the Prompt.
Here also, line 4 through 27 -> remove redundant <ins>of the</ins>

2023-12-18 15:51 UTC, epetrow commented on packages/material/scss/prompt/_variables.scss
> +/// The text color of the of the Prompt.
Same here, line 3 through 26 -> remove unnecessary <ins>of the</ins>

2023-12-18 16:08 UTC, epetrow commented
Additionally in the design the prompt actions are aligned with the TextArea which is no the case in the visual tests (there is a difference in the block padding)

2023-12-19 09:17 UTC, Juveniel commented
> Additionally in the design the prompt actions are aligned with the TextArea which is no the case in the visual tests (there is a difference in the block padding)

Discussed this with @dmanova and the issue turns out to be design related. We want the content area be spaced inwards, whereas the toolbar and action buttons are aligned.

2023-12-19 09:29 UTC, epetrow approved these changes
lgtm

2023-12-19 09:31 UTC, merged