Unify rendering columnmenu
telerik/kendo-themes pull request #4828
Opened 2023-12-21 15:44 UTC by inikolova

Related to https://github.com/telerik/kendo-themes-private/issues/189

2024-01-08 13:46 UTC, inikolova commented on packages/html/src/column-menu/column-menu.spec.tsx
> +                'k-popup k-grid-columnmenu-popup',
I like the idea for using non-related-to-the-grid classes for column menu, however the implementation in all suites relies on the `k-grid-columnmenu-popup` class. So changing this class name to `k-columnmenu-popup` would be a breaking change. If we are OK with that, I full support this idea :) 

Note: This class name is used in the PivotGrid as well.

2024-01-08 13:58 UTC, Juveniel commented on packages/html/src/column-menu/column-menu.spec.tsx
> +                'k-popup k-grid-columnmenu-popup',
It is strange for the standalone ColumnMenu spec to include other component related class names. Instead, the ColumnMenu spec can utilize the `k-columnmenu-popup` class., while the Grid instance can still rely on the additional `k-grid-columnmenu-popup` class.

2024-01-08 14:00 UTC, inikolova commented on packages/html/src/column-menu/column-menu.spec.tsx
> +                'k-popup k-grid-columnmenu-popup',
Agree :) I will update the spec / tests. Thank you

2024-01-08 14:15 UTC, inikolova commented on packages/html/src/column-menu/column-menu-filter-menu-wrapper.spec.tsx
> +                "k-group k-reset"
For styling purposes - nope. I left them for consistency, but it's better to remove them.

2024-01-08 14:21 UTC, inikolova commented on packages/html/src/column-menu/column-menu-multicheck-wrap.tsx
> +            'k-reset'
Nope; I will remove it

2024-01-15 09:44 UTC, Juveniel commented
todo:

- filter menu should be configurable
- re-add grid specific tests for the ColumnMenu
- simplify templates and tests for the extracted ColumnMenu style module

2024-01-17 12:53 UTC, epetrow requested changes

2024-01-17 12:53 UTC, epetrow commented on packages/html/src/column-menu/column-menu-expander.spec.tsx
> +        expanderIcon,
Add `{...other}` otherwise you won't have access to props from `<HTMLDivElement>` if you need them.

2024-01-17 12:53 UTC, epetrow commented on packages/html/src/column-menu/column-menu-item-content.tsx
> +        className={classNames(
Add `{...props}` or things like `style` and other props defined on `<HTMLDivElement>` won't apply if you ever need them.

2024-01-17 12:53 UTC, epetrow commented on packages/html/src/column-menu/column-menu-item-wrapper.tsx
> +        className={classNames(
Same case as the above, add `{...props}`

2024-01-17 12:53 UTC, epetrow commented on packages/html/src/column-menu/column-menu-multicheck-wrap.tsx
> +    props: React.HTMLAttributes<HTMLDivElement>
We should probably extend `React.HTMLAttributes<HTMLUListElement>` here

2024-01-17 12:53 UTC, epetrow commented on packages/html/src/column-menu/column-menu-multicheck-wrap.tsx
> +        className={classNames(
Also add `{...props}` here

2024-01-19 07:26 UTC, Juveniel commented
@inikolova we need to rebase this branch with develop to fetch the Grid spec and verify if we need to address any specific tests

2024-01-26 12:00 UTC, epetrow approved these changes
Looks good

2024-01-26 12:49 UTC, merged